name: keycloak

services:
  db:
    image: bitnami/postgresql:15
    env_file: postgres.env
    volumes:
      - db-data:/bitnami/postgresql

  server:
    image: bitnami/keycloak:23.0.6
    env_file: keycloak.env
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - db
    volumes:
      - ./certs:/certs:ro
      - ./keywind/theme/keywind:/opt/bitnami/keycloak/themes/keywind

volumes:
  db-data:
