name: Build Janus Image

on:
  push:
    branches:
      - main
    paths:
      - nextcloud/janus/**/*
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  janus:
    uses: ./.github/workflows/docker.yml
    with:
      dockerfile: nextcloud/janus/Dockerfile
      context: nextcloud/janus
      tag: spreed:janus-${{ vars.SPREED_JANUS_VERSION }}
      args: |
        JANUS_VERSION=${{ vars.SPREED_JANUS_VERSION }}
      labels: |
        org.opencontainers.image.description=meetecho/janus WebRTC server
      platforms: linux/amd64,linux/arm64
