name: Build Keycloak Image

on:
  push:
    branches:
      - main
    paths:
      - keycloak/**/*
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  keycloak:
    uses: ./.github/workflows/docker.yml
    secrets:
      DOCKER_BUILD_SECRETS: |
        gh_pat=${{ secrets.GH_PAT_KEYCLOAK_THEME }}
    with:
      dockerfile: keycloak/Dockerfile
      context: keycloak
      tag: keycloak:${{ vars.KEYCLOAK_VERSION }}
      args: |
        KEYCLOAK_VERSION=${{ vars.KEYCLOAK_VERSION }}
      labels: |
        org.opencontainers.image.description=act-coding themed Keycloak image
