name: Build Keycloak Image

on:
  push:
    branches:
      - main
    paths:
      - keycloak/**/*
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  keycloak:
    uses: ./.github/workflows/docker.yml
    with:
      dockerfile: keycloak/Dockerfile
      context: keycloak
      tag: keycloak:${{ vars.KEYCLOAK_VERSION }}
      args: |
        KEYCLOAK_VERSION=${{ vars.KEYCLOAK_VERSION }}
