name: Docker Build

on:
  workflow_call:
    inputs:
      dockerfile:
        type: string
        description: The path to the Dockerfile to use.
        required: true
      context:
        type: string
        description: The context path.
        required: true
      args:
        type: string
        description: A list of build args.
      tag:
        type: string
        description: The image tag
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  packages: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ inputs.tag }}
          labels: |
            org.opencontainers.image.vendor="act coding GbR"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          tags: ${{ inputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.args }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
