name: Build Keycloak Image

on:
  push:
    branches:
      - main
    paths:
      - keycloak/**/*
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker.yml
    with:
      dockerfile: keycloak/Dockerfile
      context: keycloak
      tag: keycloak:${{ vars.KEYCLOAK_VERSION }}
      args: |
        KEYCLOAK_VERSION=${{ vars.KEYCLOAK_VERSION }}
